# Generated by Django 5.2 on 2025-04-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admindata',
            table='myuser_admin',
        ),
        migrations.AlterModelTable(
            name='myform',
            table='myuser',
        ),
        migrations.AlterModelTable(
            name='userdata',
            table='myuser_data',
        ),
    ]
