# Generated by Django 5.2 on 2025-05-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_admindata_table_alter_myform_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admindata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='myform',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userdata',
            table=None,
        ),
    ]
