# Generated by Django 5.2 on 2025-05-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_myuser_delete_myform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdata',
            new_name='mydata',
        ),
    ]
