# Generated by Django 5.2 on 2025-05-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_userdata_mydata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminData',
            new_name='vkdata',
        ),
    ]
